[package]
name = "petite_http"
version = "0.1.0"
edition = "2024"

[dependencies]
tiny_http = "0.12"
url = "2.4.1"
idna_adapter = "=1.0.0" # Reduces dependency sprawl of "url".
percent-encoding = "2.3.2"
html-escape = "0.2.13"
tika-magic = "0.2.7"

[[example]]
name = "demo"
